/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#dbe1ff",
        "on-background": "#2a3439",
        "primary-dim": "#0048c1",
        "on-error": "#fff7f6",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#0b0f10",
        "on-tertiary-fixed": "#393c55",
        "outline": "#717c82",
        "on-secondary-fixed-variant": "#4d5d73",
        "on-tertiary-container": "#4b4e69",
        "tertiary-container": "#dcddfe",
        "surface-container-highest": "#d9e4ea",
        "on-tertiary-fixed-variant": "#555873",
        "on-secondary": "#f7f9ff",
        "error": "#9f403d",
        "secondary-fixed-dim": "#c5d6f0",
        "on-tertiary": "#fbf8ff",
        "surface-tint": "#0053db",
        "secondary-container": "#d3e4fe",
        "surface-container": "#e8eff3",
        "secondary": "#506076",
        "tertiary": "#5b5d78",
        "tertiary-dim": "#4f516c",
        "surface-container-low": "#f0f4f7",
        "primary-fixed-dim": "#c7d3ff",
        "outline-variant": "#a9b4b9",
        "inverse-on-surface": "#9a9d9f",
        "secondary-fixed": "#d3e4fe",
        "surface-bright": "#f7f9fb",
        "surface-variant": "#d9e4ea",
        "on-secondary-container": "#435368",
        "on-secondary-fixed": "#314055",
        "on-primary-fixed": "#003798",
        "tertiary-fixed": "#dcddfe",
        "on-error-container": "#752121",
        "error-container": "#fe8983",
        "primary-fixed": "#dbe1ff",
        "on-surface": "#2a3439",
        "on-surface-variant": "#566166",
        "surface": "#f7f9fb",
        "primary": "#0053db",
        "on-primary-fixed-variant": "#0050d4",
        "secondary-dim": "#44546a",
        "on-primary": "#f8f7ff",
        "tertiary-fixed-dim": "#cecfef",
        "surface-dim": "#cfdce3",
        "background": "#f7f9fb",
        "on-primary-container": "#0048bf",
        "error-dim": "#4e0309",
        "inverse-primary": "#618bff",
        "surface-container-high": "#e1e9ee"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
        inter: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
