const HARD_ADMIN_USERNAME = 'admin';
const HARD_ADMIN_PASSWORD = 'Admin@12345#OnlyOne';
const HARD_JWT_SECRET = 'CQI_HARDCORE_JWT_SECRET_2026_ONLY_ADMIN';
const DEFAULT_TOKEN_TTL_SECONDS = 60 * 60 * 24 * 30; // 30 days

module.exports = {
  HARD_ADMIN_USERNAME,
  HARD_ADMIN_PASSWORD,
  HARD_JWT_SECRET,
  DEFAULT_TOKEN_TTL_SECONDS,
};

